#!/usr/bin/env bun
/**
 * Mirror packages/ui/src/styles/tokens.css into packages/ui/src/styles/tokens-css.ts as an exported string so the CDN entry (src/cdn.ts) can inject the token contract into document.head without a separate network request. tokens.css stays the single source of truth; this codegen is regenerated on every build and from the release workflow. Re-run via `bun run scripts/sync-tokens.ts`.
 */
import { readFile, writeFile } from 'node:fs/promises';

const CSS_PATH = 'packages/ui/src/styles/tokens.css';
const OUT_PATH = 'packages/ui/src/styles/tokens-css.ts';

async function main() {
	const css = await readFile(CSS_PATH, 'utf8');
	// Template literals are delimited by backticks and interpolate ${...}; escape
	// both plus the backslash so the emitted string is byte-identical to the CSS.
	const escaped = css
		.replace(/\\/g, '\\\\')
		.replace(/`/g, '\\`')
		.replace(/\$\{/g, '\\${');
	const body = `// Generated by scripts/sync-tokens.ts from tokens.css. Do not edit.\nexport const ROXY_UI_TOKENS_CSS = \`${escaped}\`;\n`;
	await writeFile(OUT_PATH, body);
	console.log(`Wrote ${OUT_PATH} (${css.length} bytes of CSS).`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
