#!/usr/bin/env bun
/**
 * Pull the API's field-label maps and emit one side-effect module per language.
 *
 * @remarks
 * **Build time, not run time, and that is the whole decision.** These labels translate request
 * field names that come from the OpenAPI spec, and the form already consumes that spec as
 * version-pinned artifacts baked at build. Fetching labels from the browser instead would buy no
 * decoupling the schema slices do not already have, and would cost three things that matter on an
 * embed: an extra request on the critical path, a dependency on the API being reachable for a
 * purely cosmetic payload, and a visible flash where every form paints English and then re-renders
 * translated a moment later. Baking them removes all three.
 *
 * @remarks
 * They ride the EXISTING per-language payload rather than a new file. A page that wants Spanish
 * already loads `locales/es.js`; this adds the labels to that same download, so the request count
 * is unchanged and English still ships nothing. Refresh point is `bun run generate`, the same
 * command that refreshes the spec, because they are the same fact from one source.
 *
 * @remarks
 * A build with no reachable API keeps whatever is on disk and warns. That matters: the endpoint is
 * newer than this script, so a build running before the API ships must not fail, and a transient
 * outage must not silently blank a shipped catalogue.
 *
 * @remarks
 * `--check` is the drift gate: it regenerates every catalogue from the LIVE endpoint in memory and
 * fails when a committed module differs, so a label the API changed cannot ship stale from here.
 * It ignores the hermetic flag on purpose (drift is by definition between the live API and the
 * tree), and an unreachable API is a failure rather than a pass, because a check that passes when
 * it cannot check is the non-hermetic build with a hermetic name all over again. Output is
 * formatted through biome before writing or comparing, so the tree never shows a pure reformat as
 * a change and the comparison is byte-exact against what the hook would have committed.
 */
import { existsSync } from 'node:fs';
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { API_LANGUAGES } from '../packages/ui/src/generated/api-languages.js';
import { humanize } from '../packages/ui/src/utils/string.js';

const API_BASE = process.env.ROXY_API_BASE ?? 'https://roxyapi.com/api/v2';
const LOCALES_DIR = 'packages/ui/src/locales';
const OUT_DIR = `${LOCALES_DIR}/field-labels`;
/** English ships no payload, so the API English names the form prints are compiled in, and only where they differ from what `humanize` would print anyway. */
const EN_OUT = 'packages/ui/src/generated/field-labels-en.ts';

/**
 * Derived twice over, never mirrored by hand: a language the API serves AND ships a chrome
 * payload for. English is absent because it needs no payload.
 *
 * @remarks
 * A hand-kept copy is checked against itself, and the language somebody forgets to add to it is
 * the one that then ships with unlabelled fields and no error anywhere (lesson 23). `lang` on the
 * spec is the only place the set of API languages is decided, so read it from there.
 *
 * The second half is the directory, because a labels module is imported by its language's chrome
 * payload and by nothing else: written for a language with no payload it is unreachable code that
 * ships in the tarball and no build reports. The set the API serves can therefore run ahead of the
 * set catalogued here, which it does whenever a language lands upstream before its chrome does.
 * `tests/i18n.test.ts` is what stops that drifting silently: it holds this directory to the
 * shipped catalogues, and holds the shipped catalogues to the API's own list bar a declared
 * exception per language.
 */
const CATALOGUED = new Set(
	(await readdir(LOCALES_DIR))
		.filter((f) => f.endsWith('.ts'))
		.map((f) => f.replace(/\.ts$/, '')),
);
const LANGS = API_LANGUAGES.filter((l) => l !== 'en' && CATALOGUED.has(l));

interface LabelPayload {
	fields?: Record<string, string>;
	enums?: Record<string, string>;
}

function emit(lang: string, payload: LabelPayload): string {
	const fields = JSON.stringify(payload.fields ?? {}, null, '\t');
	const enums = JSON.stringify(payload.enums ?? {}, null, '\t');
	return `/**
 * GENERATED by \`bun run scripts/sync-field-labels.ts\`. Do not edit.
 *
 * @remarks
 * Labels for request field names and their selectable options, in ${lang}. Importing this module
 * registers them and re-renders every mounted form, exactly like the chrome catalogue beside it.
 * Regenerate with \`bun run generate\`; the source of truth is the API, not this file.
 */

import { registerFieldLabels } from '../../i18n/registry.js';

registerFieldLabels('${lang}', {
\tfields: ${fields.replace(/\n/g, '\n\t')},
\tenums: ${enums.replace(/\n/g, '\n\t')},
});
`;
}

/** The API English label of every field whose label is not simply its humanized name, sorted for a stable diff. */
function emitEnglish(payload: LabelPayload): string {
	const differing = Object.entries(payload.fields ?? {})
		.filter(([name, label]) => label !== humanize(name))
		.sort(([a], [b]) => a.localeCompare(b));
	return `/**
 * GENERATED by \`bun run scripts/sync-field-labels.ts\`. Do not edit.
 *
 * @remarks
 * The API English label of every request field whose label differs from its humanized wire name, which the form prints on an English page and wherever a translated payload carries no label of its own.
 */
export const EN_FIELD_LABELS: Record<string, string> = ${JSON.stringify(Object.fromEntries(differing), null, '\t')};
`;
}

/** Every catalogue this script writes: one per shipped language plus the compiled-in English override. */
const TARGETS = [
	...LANGS.map((lang) => ({
		lang,
		out: `${OUT_DIR}/${lang}.ts`,
		emit: (p: LabelPayload) => emit(lang, p),
	})),
	{ lang: 'en', out: EN_OUT, emit: emitEnglish },
];

const CHECK = process.argv.includes('--check');

/** The generated text as biome commits it, so a diff is content and never formatting. */
function formatted(path: string, text: string): string {
	const run = Bun.spawnSync(
		['bun', 'x', 'biome', 'format', `--stdin-file-path=${path}`],
		{
			stdin: Buffer.from(text),
		},
	);
	if (run.exitCode !== 0)
		throw new Error(`biome format failed: ${run.stderr.toString()}`);
	return run.stdout.toString();
}

async function fetchLabels(lang: string): Promise<LabelPayload> {
	const res = await fetch(`${API_BASE}/languages/field-labels?lang=${lang}`, {
		signal: AbortSignal.timeout(20_000),
	});
	if (!res.ok) throw new Error(`HTTP ${res.status}`);
	const body = (await res.json()) as LabelPayload;
	if (!body.fields || Object.keys(body.fields).length === 0) {
		throw new Error('payload carried no fields');
	}
	return body;
}

if (CHECK) {
	const drifted: string[] = [];
	for (const { lang, out, emit: write } of TARGETS) {
		let expected: string;
		try {
			expected = formatted(out, write(await fetchLabels(lang)));
		} catch (err) {
			console.error(
				`${lang}: ${err instanceof Error ? err.message : String(err)}`,
			);
			process.exit(1);
		}
		const committed = existsSync(out) ? await Bun.file(out).text() : '';
		if (committed !== expected) drifted.push(lang);
	}
	if (drifted.length > 0) {
		console.error(
			`Field labels drifted from the live API: ${drifted.join(', ')}. Run 'bun run labels:sync' and commit.`,
		);
		process.exit(1);
	}
	console.log(
		`Field labels match the live API across ${TARGETS.length} catalogue(s).`,
	);
	process.exit(0);
}

await mkdir(OUT_DIR, { recursive: true });

// The same hermetic switch `generate.ts` honours for the spec and the MCP tool list: with it set,
// the committed catalogues are the input, so an install or a CI run never rewrites them from a
// live API that may have moved. Refreshing them is the release workflow's job, which runs online.
if (process.env.ROXYAPI_SPEC_FILE) {
	console.log(
		`Keeping ${OUT_DIR}/*.ts and ${EN_OUT} (offline, ROXYAPI_SPEC_FILE)`,
	);
	process.exit(0);
}

let written = 0;
let kept = 0;
for (const { lang, out, emit: write } of TARGETS) {
	try {
		await writeFile(out, formatted(out, write(await fetchLabels(lang))));
		written++;
	} catch (err) {
		const detail = err instanceof Error ? err.message : String(err);
		if (existsSync(out)) {
			console.warn(`  ${lang}: ${detail} — keeping the committed catalogue`);
			kept++;
		} else {
			// No payload and nothing on disk. Emit an empty catalogue so the import still
			// resolves and the form falls back to humanize().
			await writeFile(out, formatted(out, write({ fields: {}, enums: {} })));
			console.warn(
				`  ${lang}: ${detail} — wrote an EMPTY catalogue (form falls back)`,
			);
			written++;
		}
	}
}

console.log(
	`Field labels: ${written} written, ${kept} kept from disk, across ${TARGETS.length} catalogue(s).`,
);
