#!/usr/bin/env bun
/**
 * Mirror the TypeScript manifest into apps/docs/manifest.js so the static docs site can read it without a build step. CI fails on drift.
 *
 * @remarks
 * Three browser globals are emitted from the same generated file: `window.ROXY_COMPONENTS` (the component manifest), `window.ROXY_ENDPOINT_BINDINGS` (the generated component-to-endpoint map), and `window.ROXY_THEME_PRESETS` (the theme palette data). The demo's `components-manifest.js` reads the second to derive the Embed tab snippet for every endpoint-bound card, so a binding change flows to the demo with no per-card edit; `page.js` reads the third to drive the customizer preset picker, so a palette edit flows to the demo with no hand-copied hexes.
 */
import { writeFile } from 'node:fs/promises';
import { ENDPOINT_BINDINGS } from '../packages/ui/src/generated/endpoint-bindings.js';
import { ROXY_COMPONENTS } from '../packages/ui/src/manifest.js';
import {
	type PaletteName,
	type PaletteTokens,
	ROXY_PALETTES,
	SHARED_THEME,
} from '../packages/ui/src/styles/palettes.js';

const OUT_PATH = 'apps/docs/manifest.js';

/** The overrides the customizer applies for one mode: the palette tokens plus the mode-shared danger, in token order. `accent-ink` and `ring` derive from `accent`, so the demo never emits them. */
function presetMode(t: PaletteTokens, mode: 'light' | 'dark') {
	return {
		accent: t.accent,
		secondary: t.secondary,
		danger: SHARED_THEME.danger[mode],
		bg: t.bg,
		surface: t.surface,
		fg: t.fg,
		muted: t.muted,
		border: t.border,
	};
}

const THEME_PRESETS = Object.fromEntries(
	(Object.keys(ROXY_PALETTES) as PaletteName[]).map((name) => [
		name,
		{
			file: `${name}.css`,
			light: presetMode(ROXY_PALETTES[name].light, 'light'),
			dark: presetMode(ROXY_PALETTES[name].dark, 'dark'),
		},
	]),
);

async function main() {
	const body =
		'// Generated by scripts/sync-manifest.ts. Do not edit.\n' +
		`window.ROXY_COMPONENTS = ${JSON.stringify(ROXY_COMPONENTS, null, 2)};\n` +
		`window.ROXY_ENDPOINT_BINDINGS = ${JSON.stringify(ENDPOINT_BINDINGS, null, 2)};\n` +
		`window.ROXY_THEME_PRESETS = ${JSON.stringify(THEME_PRESETS, null, 2)};\n`;
	await writeFile(OUT_PATH, body);
	console.log(
		`Wrote ${OUT_PATH} (${ROXY_COMPONENTS.length} components, ${Object.keys(ENDPOINT_BINDINGS).length} bound tags, ${Object.keys(THEME_PRESETS).length} theme presets).`,
	);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
