#!/usr/bin/env bun
/**
 * Mirror the TypeScript manifest into apps/docs/manifest.js so the static docs site can read it without a build step. CI fails on drift.
 *
 * @remarks
 * Two browser globals are emitted from the same generated file: `window.ROXY_COMPONENTS` (the component manifest) and `window.ROXY_ENDPOINT_BINDINGS` (the generated component-to-endpoint map). The demo's `components-manifest.js` reads the second to derive the Embed tab snippet for every endpoint-bound card, so a binding change flows to the demo with no per-card edit.
 */
import { writeFile } from 'node:fs/promises';
import { ENDPOINT_BINDINGS } from '../packages/ui/src/generated/endpoint-bindings.js';
import { ROXY_COMPONENTS } from '../packages/ui/src/manifest.js';

const OUT_PATH = 'apps/docs/manifest.js';

async function main() {
	const body =
		'// Generated by scripts/sync-manifest.ts. Do not edit.\n' +
		`window.ROXY_COMPONENTS = ${JSON.stringify(ROXY_COMPONENTS, null, 2)};\n` +
		`window.ROXY_ENDPOINT_BINDINGS = ${JSON.stringify(ENDPOINT_BINDINGS, null, 2)};\n`;
	await writeFile(OUT_PATH, body);
	console.log(
		`Wrote ${OUT_PATH} (${ROXY_COMPONENTS.length} components, ${Object.keys(ENDPOINT_BINDINGS).length} bound tags).`,
	);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
