#!/usr/bin/env bun
/**
 * Pull the API's field-label maps and emit one side-effect module per language.
 *
 * @remarks
 * **Build time, not run time, and that is the whole decision.** These labels translate request
 * field names that come from the OpenAPI spec, and the form already consumes that spec as
 * version-pinned artifacts baked at build. Fetching labels from the browser instead would buy no
 * decoupling the schema slices do not already have, and would cost three things that matter on an
 * embed: an extra request on the critical path, a dependency on the API being reachable for a
 * purely cosmetic payload, and a visible flash where every form paints English and then re-renders
 * translated a moment later. Baking them removes all three.
 *
 * @remarks
 * They ride the EXISTING per-language payload rather than a new file. A page that wants Spanish
 * already loads `locales/es.js`; this adds the labels to that same download, so the request count
 * is unchanged and English still ships nothing. Refresh point is `bun run generate`, the same
 * command that refreshes the spec, because they are the same fact from one source.
 *
 * @remarks
 * A build with no reachable API keeps whatever is on disk and warns. That matters: the endpoint is
 * newer than this script, so a build running before the API ships must not fail, and a transient
 * outage must not silently blank a shipped catalogue.
 */
import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';

const API_BASE = process.env.ROXY_API_BASE ?? 'https://roxyapi.com/api/v2';
const OUT_DIR = 'packages/ui/src/locales/field-labels';

/** Mirrors the locale files that exist; English is deliberately absent (it needs no payload). */
const LANGS = ['de', 'es', 'fr', 'hi', 'pt', 'ru', 'tr'] as const;

interface LabelPayload {
	fields?: Record<string, string>;
	enums?: Record<string, string>;
}

function emit(lang: string, payload: LabelPayload): string {
	const fields = JSON.stringify(payload.fields ?? {}, null, '\t');
	const enums = JSON.stringify(payload.enums ?? {}, null, '\t');
	return `/**
 * GENERATED by \`bun run scripts/sync-field-labels.ts\`. Do not edit.
 *
 * @remarks
 * Labels for request field names and their selectable options, in ${lang}. Importing this module
 * registers them and re-renders every mounted form, exactly like the chrome catalogue beside it.
 * Regenerate with \`bun run generate\`; the source of truth is the API, not this file.
 */

import { registerFieldLabels } from '../../i18n/registry.js';

registerFieldLabels('${lang}', {
\tfields: ${fields.replace(/\n/g, '\n\t')},
\tenums: ${enums.replace(/\n/g, '\n\t')},
});
`;
}

await mkdir(OUT_DIR, { recursive: true });

let written = 0;
let kept = 0;
for (const lang of LANGS) {
	const out = `${OUT_DIR}/${lang}.ts`;
	try {
		const res = await fetch(`${API_BASE}/languages/field-labels?lang=${lang}`, {
			signal: AbortSignal.timeout(20_000),
		});
		if (!res.ok) throw new Error(`HTTP ${res.status}`);
		const body = (await res.json()) as LabelPayload;
		if (!body.fields || Object.keys(body.fields).length === 0) {
			throw new Error('payload carried no fields');
		}
		await writeFile(out, emit(lang, body));
		written++;
	} catch (err) {
		const detail = err instanceof Error ? err.message : String(err);
		if (existsSync(out)) {
			console.warn(`  ${lang}: ${detail} — keeping the committed catalogue`);
			kept++;
		} else {
			// No payload and nothing on disk. Emit an empty registration so the import in
			// `locales/${lang}.ts` still resolves and the form falls back to humanize().
			await writeFile(out, emit(lang, { fields: {}, enums: {} }));
			console.warn(
				`  ${lang}: ${detail} — wrote an EMPTY catalogue (form falls back)`,
			);
			written++;
		}
	}
}

console.log(
	`Field labels: ${written} written, ${kept} kept from disk, across ${LANGS.length} language(s).`,
);
