#!/usr/bin/env bun
/**
 * Mirror packages/ui/package.json version into packages/ui/src/version.ts so
 * runtime + downstream codegen (build-react, build-widgets) read one source.
 * Re-run on every build and from the release workflow after the version bump.
 */
import { readFile, writeFile } from 'node:fs/promises';

const PKG_PATH = 'packages/ui/package.json';
const OUT_PATH = 'packages/ui/src/version.ts';

async function main() {
	const pkg = JSON.parse(await readFile(PKG_PATH, 'utf8')) as {
		version: string;
	};
	if (typeof pkg.version !== 'string' || !/^\d+\.\d+\.\d+/.test(pkg.version)) {
		throw new Error(`Invalid version in ${PKG_PATH}: ${pkg.version}`);
	}
	const body = `// Generated by scripts/sync-version.ts. Do not edit.\nexport const ROXY_UI_VERSION = '${pkg.version}';\n`;
	await writeFile(OUT_PATH, body);
	console.log(`Wrote ${OUT_PATH} (${pkg.version}).`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
