#!/usr/bin/env bun
/**
 * Generate the shipped theme preset CSS files from the palette data. One file per palette at packages/ui/src/styles/themes/{name}.css, each reassigning only --roxy-* tokens in the same four-trigger structure as tokens.css (light default, OS-dark, explicit-light opt-out, explicit-dark opt-in), all at :where() zero specificity. palettes.ts is the single source of truth; this codegen is regenerated on every build and from the release workflow. Re-run via `bun run scripts/sync-themes.ts`.
 *
 * @remarks Values are emitted un-wrapped and the file is then passed through biome so long font stacks wrap exactly as biome would format a hand-written file, keeping the generated output stable under `bun run check` and the pre-push codegen gate. The rosewater palette is written as themes/practitioner.css to preserve the shipped CDN URL.
 */
import { execSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import {
	type Palette,
	type PaletteName,
	type PaletteTokens,
	ROXY_PALETTES,
	SELF_HOSTED_FACES,
	SELF_HOSTED_FONT_PALETTE,
	SHARED_THEME,
} from '../packages/ui/src/styles/palettes.js';

const OUT_DIR = 'packages/ui/src/styles/themes';
const PKG_PATH = 'packages/ui/package.json';

const LIGHT_ACCENT_INK = 'color-mix(in oklab, var(--roxy-accent) 70%, black)';
const DARK_ACCENT_INK = 'var(--roxy-accent)';

const SECONDARY_COMMENT =
	'\t/* Secondary ink (form labels, generic-renderer text, chart strokes): a warm tone between fg and muted so it stays stronger than help text. Without this override the stock slate leaks through and reads bluish on the warm palette. */';

const LIGHT_SELECTOR =
	':where(\n\t:root[data-theme="light"],\n\t[data-theme="light"],\n\t:root.light,\n\t.light,\n\t:host([data-theme="light"])\n)';
const DARK_SELECTOR =
	':where(\n\t:root[data-theme="dark"],\n\t[data-theme="dark"],\n\t:root.dark,\n\t.dark,\n\t:host([data-theme="dark"])\n)';

/** Colour declarations for one mode. `indent` is the leading whitespace per line; the first block adds --roxy-ring plus the secondary comment, the opt-out/opt-in blocks omit both. */
function colorTokens(
	t: PaletteTokens,
	mode: 'light' | 'dark',
	indent: string,
	opts: { ring: boolean; secondaryComment: boolean },
): string {
	const accentInk = mode === 'light' ? LIGHT_ACCENT_INK : DARK_ACCENT_INK;
	const danger = SHARED_THEME.danger[mode];
	const lines = [
		`${indent}--roxy-accent: ${t.accent};`,
		`${indent}--roxy-accent-ink: ${accentInk};`,
	];
	if (opts.ring) lines.push(`${indent}--roxy-ring: var(--roxy-accent);`);
	if (opts.secondaryComment) lines.push(SECONDARY_COMMENT);
	lines.push(
		`${indent}--roxy-secondary: ${t.secondary};`,
		`${indent}--roxy-danger: ${danger};`,
		'',
		`${indent}--roxy-bg: ${t.bg};`,
		`${indent}--roxy-surface: ${t.surface};`,
		`${indent}--roxy-fg: ${t.fg};`,
		`${indent}--roxy-muted: ${t.muted};`,
		`${indent}--roxy-border: ${t.border};`,
	);
	return lines.join('\n');
}

function header(name: PaletteName, selfHosted: boolean): string {
	const title = name[0].toUpperCase() + name.slice(1);
	const fontLines = selfHosted
		? [
				' * Fonts are self-hosted: both families are OFL, bundled under',
				' * dist/styles/fonts and served from jsDelivr pinned to this package',
				' * version, so linking this file makes no request to a third-party font',
				' * host. The OFL license text for each font family ships beside its files.',
			]
		: [
				' * Fonts are loaded below via one Google Fonts @import (both families are',
				' * OFL, loaded from Google, never bundled here). To load them with markup',
				' * instead, drop the @import line and add these to the page <head>:',
				' *',
				' *   <link rel="preconnect" href="https://fonts.googleapis.com">',
				' *   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
				` *   <link rel="stylesheet" href="${SHARED_THEME.fontImport}">`,
			];
	return [
		'/*',
		` * ${title} theme preset for Roxy UI. GENERATED by scripts/sync-themes.ts`,
		' * from src/styles/palettes.ts. Do not edit; change the palette data and',
		' * rerun the codegen.',
		' *',
		' * It only reassigns --roxy-* tokens, so it composes with the core token',
		' * contract instead of replacing it: link it AFTER the base tokens (or the',
		' * CDN bundle that injects them) and every component on the page adopts the',
		' * look. Light and dark blocks mirror the trigger structure of tokens.css',
		' * exactly (OS preference, [data-theme] / .dark opt-in, and the explicit-',
		' * light opt-out), all at :where() zero specificity so a per-page override',
		' * still wins.',
		' *',
		...fontLines,
		' *',
		' * To use the whole preset with one line instead of copying tokens, link',
		' * the file:',
		' *',
		` *   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@roxyapi/ui@latest/dist/styles/themes/${name}.css">`,
		' */',
	].join('\n');
}

/** `@font-face` blocks for the self-hosting palette, one per subset file, mirroring the unicode-range split Google Fonts itself serves so a page still downloads only the script it renders. `fontBase` is the jsDelivr package path pinned to the version this build is running for, immutable exactly like the tag-pinned preview URLs in sync-catalog.ts. */
function selfHostedFontFaces(fontBase: string): string {
	return SELF_HOSTED_FACES.map((f) =>
		[
			'@font-face {',
			`\tfont-family: '${f.family}';`,
			'\tfont-style: normal;',
			'\tfont-weight: 400 600;',
			'\tfont-display: swap;',
			`\tsrc: url('${fontBase}/${f.file}') format('woff2');`,
			`\tunicode-range: ${f.unicodeRange};`,
			'}',
		].join('\n'),
	).join('\n\n');
}

function themeCss(name: PaletteName, p: Palette, fontBase: string): string {
	const selfHosted = name === SELF_HOSTED_FONT_PALETTE;
	const firstBlock = [
		':where(:root, :host) {',
		`\t--roxy-font-sans: ${SHARED_THEME.fontSans};`,
		`\t--roxy-font-display: ${SHARED_THEME.fontDisplay};`,
		'',
		`\t--roxy-radius-sm: ${SHARED_THEME.radius.sm};`,
		`\t--roxy-radius-md: ${SHARED_THEME.radius.md};`,
		`\t--roxy-radius-lg: ${SHARED_THEME.radius.lg};`,
		'',
		`\t--roxy-shadow-sm: ${SHARED_THEME.shadow.sm};`,
		`\t--roxy-shadow-md: ${SHARED_THEME.shadow.md};`,
		`\t--roxy-shadow-lg: ${SHARED_THEME.shadow.lg};`,
		'',
		colorTokens(p.light, 'light', '\t', { ring: true, secondaryComment: true }),
		'}',
	].join('\n');

	const mediaBlock = [
		'@media (prefers-color-scheme: dark) {',
		'\t:where(:root, :host) {',
		colorTokens(p.dark, 'dark', '\t\t', {
			ring: false,
			secondaryComment: false,
		}),
		'\t}',
		'}',
	].join('\n');

	const lightOptOut = [
		`${LIGHT_SELECTOR} {`,
		colorTokens(p.light, 'light', '\t', {
			ring: false,
			secondaryComment: false,
		}),
		'}',
	].join('\n');

	const darkOptIn = [
		`${DARK_SELECTOR} {`,
		colorTokens(p.dark, 'dark', '\t', { ring: false, secondaryComment: false }),
		'}',
	].join('\n');

	const fontsBlock = selfHosted
		? selfHostedFontFaces(fontBase)
		: `@import url("${SHARED_THEME.fontImport}");`;

	return [
		header(name, selfHosted),
		fontsBlock,
		'',
		'/* Light defaults. Fonts, radius, and shadow do not vary by theme, so they are\n * set once here and inherited by the dark blocks unchanged. */',
		firstBlock,
		'',
		'/* Dark theme via system preference. Mirrors tokens.css: only the theme-varying\n * tokens are reassigned; accent-ink follows the accent (already legible on the\n * dark surface) rather than mixing toward black. */',
		mediaBlock,
		'',
		'/* Light opt-out: beats the OS-dark block when the host explicitly chooses light. */',
		lightOptOut,
		'',
		'/* Dark theme via explicit opt-in ([data-theme=dark] or .dark on any ancestor). */',
		darkOptIn,
		'',
	].join('\n');
}

async function main() {
	// Pinned to THIS build's version, immutable exactly like the tag-pinned
	// preview URLs sync-catalog.ts writes: a release regenerates this file with
	// its own version baked in, in lockstep with what actually publishes.
	const pkg = JSON.parse(await readFile(PKG_PATH, 'utf8')) as {
		version: string;
	};
	const fontBase = `https://cdn.jsdelivr.net/npm/@roxyapi/ui@${pkg.version}/dist/styles/fonts`;

	const names = Object.keys(ROXY_PALETTES) as PaletteName[];
	for (const name of names) {
		await writeFile(
			`${OUT_DIR}/${name}.css`,
			themeCss(name, ROXY_PALETTES[name], fontBase),
		);
	}
	// Wrap long font stacks the way biome would format a hand-written file, so the
	// committed CSS is stable under `bun run check` and the pre-push codegen gate.
	execSync(`bunx biome format --write ${OUT_DIR}`, { stdio: 'inherit' });
	console.log(`Wrote ${names.length} theme files to ${OUT_DIR}.`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
