#!/usr/bin/env bun
/**
 * Generate packages/ui/src/generated/endpoint-bindings.ts by joining this
 * repo's own component-to-endpoint map (scripts/bindings.config.ts) with the
 * RoxyAPI spec (specs/openapi.json) on `operationId`, resolving each binding's
 * HTTP method + path from the spec. The API spec stays UI-agnostic; the binding
 * is owned here. Generating it is what keeps the tag-to-endpoint mapping from
 * drifting: a hand-kept endpoint string in src/manifest.ts cannot be checked
 * against the spec, and this can.
 *
 * Reads specs/openapi.json (refreshed by scripts/generate.ts from the live
 * spec). Run standalone with `bun run bindings:sync`; also runs as a step of
 * `bun run build` and `bun run generate`. CI fails on drift.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { UI_BINDINGS } from './bindings.config.js';

const SPEC_PATH = 'specs/openapi.json';
const OUT_PATH = 'packages/ui/src/generated/endpoint-bindings.ts';

interface EndpointBinding {
	operationId: string;
	method: string;
	path: string;
	attrs?: Record<string, string>;
}

const spec = JSON.parse(await Bun.file(SPEC_PATH).text()) as {
	paths: Record<string, Record<string, { operationId?: string }>>;
};

// operationId -> { method, path }, resolved from the spec.
const located: Record<string, { method: string; path: string }> = {};
for (const [path, methods] of Object.entries(spec.paths)) {
	for (const [method, op] of Object.entries(methods)) {
		if (op?.operationId)
			located[op.operationId] = { method: method.toUpperCase(), path };
	}
}

const byTag: Record<string, EndpointBinding[]> = {};
const missing: string[] = [];
for (const [operationId, components] of Object.entries(UI_BINDINGS)) {
	const where = located[operationId];
	if (!where) {
		missing.push(operationId);
		continue;
	}
	for (const { component, attrs } of components) {
		let list = byTag[component];
		if (!list) {
			list = [];
			byTag[component] = list;
		}
		list.push({
			operationId,
			method: where.method,
			path: where.path,
			...(attrs ? { attrs } : {}),
		});
	}
}

/**
 * Stable output: tags sorted alphabetically for a readable diff, but each tag's endpoints kept in DECLARATION order.
 *
 * @remarks
 * **The first binding per tag is the DEFAULT** everywhere it matters: the widget map, the one-tag `data-roxy-widget` div, the demo Embed tab, and the hosted `/embed/{slug}` shell all take `endpoints[0]`. So the order here is semantics, not formatting.
 *
 * Sorting these by path used to look tidy and silently picked the default alphabetically, which is unrelated to what a reader wants. It gave `moon-phase` the year-and-month calendar form instead of today's phase, `forecast-timeline` the significant-dates list instead of the timeline it is named after, `numerology-card` birth-day instead of life-path, and `tarot-spread` a raw draw instead of the three-card spread: twelve components in all.
 *
 * `UI_BINDINGS` already lists each component's endpoints in the order a reader would want them, so declaration order IS the intent. Preserve it. Only the tag keys are sorted, and those are never read positionally.
 */
const sorted: Record<string, EndpointBinding[]> = {};
for (const tag of Object.keys(byTag).sort()) {
	sorted[tag] = byTag[tag];
}

const tagCount = Object.keys(sorted).length;
const endpointCount = Object.values(sorted).reduce((n, b) => n + b.length, 0);

const body = `// Generated by scripts/sync-bindings.ts (bindings.config.ts joined with ${SPEC_PATH}). Do not edit.

/**
 * One endpoint a component can render. \`path\` is the full spec path (leading
 * slash); the self-fetch \`data-endpoint\` value is that path without the
 * leading slash. \`attrs\` are the config attributes that select this variant on
 * a multi-endpoint component.
 */
export interface EndpointBinding {
  operationId: string;
  method: string;
  path: string;
  attrs?: Record<string, string>;
}

/** Component tag -> every endpoint whose response it renders. */
export const ENDPOINT_BINDINGS: Record<string, EndpointBinding[]> = ${JSON.stringify(sorted, null, 2)};
`;

await mkdir('packages/ui/src/generated', { recursive: true });
await writeFile(OUT_PATH, body);
console.log(
	`Wrote ${OUT_PATH}: ${endpointCount} endpoints across ${tagCount} components.`,
);

if (missing.length > 0) {
	console.warn(
		`! ${missing.length} binding(s) reference an operationId absent from ${SPEC_PATH} (rename or stale spec):\n  ${missing.join('\n  ')}`,
	);
	process.exit(1);
}
