#!/usr/bin/env bun
/**
 * Mirror the TypeScript manifest into apps/docs/manifest.js so the static
 * docs site can read it without a build step. CI fails on drift.
 */
import { writeFile } from 'node:fs/promises';
import { ROXY_COMPONENTS } from '../packages/ui/src/manifest.js';

const OUT_PATH = 'apps/docs/manifest.js';

async function main() {
	const body =
		'// Generated by scripts/sync-manifest.ts. Do not edit.\n' +
		`window.ROXY_COMPONENTS = ${JSON.stringify(ROXY_COMPONENTS, null, 2)};\n`;
	await writeFile(OUT_PATH, body);
	console.log(`Wrote ${OUT_PATH} (${ROXY_COMPONENTS.length} entries).`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
